version: "3.9"
services:
  app:
    container_name: my-nest-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "run", "test"]
